#!/bin/bash -e

proj=$(ls *.geo | sed 's/\..*//')
kn=$(head -1 $proj.geo | egrep -o '[0-9\.e+-]+')

join() {
    local IFS=.
    echo "$*"
}

run_app() {
    local log=log.$(join $*)
    if test ! -f $log; then
        echo "Running $* at $(pwd)"
        $* &> $log
    else
        echo "$(pwd)/$log is already exist!"
    fi
}

change_field() {
    file=$1
    bc=$2
    old=$file.old
    mv $file $old
    awk '
BEGIN {
    type=0
}
{
    if ($1 == "outer" || $1 == "inner") type=1;
    if ($1 == "type" && type) {
        print "        type            '$bc';";
        type = 0;
    } else print;
}' $old > $file
}

window=10.0
[[ $# > 0 ]] && window=$1
echo "Window for averaging: $window"

echo "Running out2foam.py"
$HOME/kesolver/tools/out2foam.py $proj --kn=$kn
cat ../controlDict | sed 's/\( *window *\)[0-9\.]*;/\1'$window';/' >> system/controlDict

run_app correctBC
run_app calcPressure
run_app emptyFoam

#last=$(foamListTimes | tail -1)
#change_field $last/TMean extrapolatedGradient
#change_field $last/UMean extrapolatedSlipGradient #slip
#run_app correctBC -latestTime
#run_app foamToVTK -latestTime

run_app foamToTecplot360 -latestTime

echo ok

